#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --cpus-per-task=20
#SBATCH --mem=64000                     # Memory requested
#SBATCH --qos=normal
#SBATCH --time=0-24:00:00
#SBATCH --mail-type=ALL              # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=eenbody@tulane.edu
#SBATCH -e ./logs/transdecoder.err           # File to which STDERR will be written
#SBATCH -o ./logs/transdecoder.out         # File to which STDOUT will be written
#SBATCH -J transdecoder    # Job name



TRANS_DATA=/home/eenbody/Enbody_WD/WSFW_DDIG/RNAseq_WD/Guided_Trinity/trinity_gg/Trinity-GG.fasta
WORK_D=/home/eenbody/RNAseq_WD/Trinotate

cd $WORK_D

TransDecoder.LongOrfs -t $TRANS_DATA
TransDecoder.Predict -t $TRANS_DATA
